/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BirthdayPhotoBoothGurgaonRouteImport } from './routes/birthday-photo-booth-gurgaon'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporatePhotoBoothNoidaRouteImport } from './routes/corporate-photo-booth-noida'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OurWorkRouteImport } from './routes/our-work'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PhotoBoothRentalDelhiRouteImport } from './routes/photo-booth-rental-delhi'
import { Route as PhotoBoothRentalDelhiNcrRouteImport } from './routes/photo-booth-rental-delhi-ncr'
import { Route as PhotoBoothRentalGreaterNoidaRouteImport } from './routes/photo-booth-rental-greater-noida'
import { Route as PhotoBoothRentalGurgaonRouteImport } from './routes/photo-booth-rental-gurgaon'
import { Route as PhotoBoothRentalNoidaRouteImport } from './routes/photo-booth-rental-noida'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as WeddingPhotoBoothDelhiNcrRouteImport } from './routes/wedding-photo-booth-delhi-ncr'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsBirthdaysRouteImport } from './routes/events.birthdays'
import { Route as EventsCorporateRouteImport } from './routes/events.corporate'
import { Route as EventsWeddingsRouteImport } from './routes/events.weddings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdayPhotoBoothGurgaonRoute =
  BirthdayPhotoBoothGurgaonRouteImport.update({
    id: '/birthday-photo-booth-gurgaon',
    path: '/birthday-photo-booth-gurgaon',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporatePhotoBoothNoidaRoute =
  CorporatePhotoBoothNoidaRouteImport.update({
    id: '/corporate-photo-booth-noida',
    path: '/corporate-photo-booth-noida',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoBoothRentalDelhiRoute = PhotoBoothRentalDelhiRouteImport.update({
  id: '/photo-booth-rental-delhi',
  path: '/photo-booth-rental-delhi',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoBoothRentalDelhiNcrRoute =
  PhotoBoothRentalDelhiNcrRouteImport.update({
    id: '/photo-booth-rental-delhi-ncr',
    path: '/photo-booth-rental-delhi-ncr',
    getParentRoute: () => rootRouteImport,
  } as any)
const PhotoBoothRentalGreaterNoidaRoute =
  PhotoBoothRentalGreaterNoidaRouteImport.update({
    id: '/photo-booth-rental-greater-noida',
    path: '/photo-booth-rental-greater-noida',
    getParentRoute: () => rootRouteImport,
  } as any)
const PhotoBoothRentalGurgaonRoute = PhotoBoothRentalGurgaonRouteImport.update({
  id: '/photo-booth-rental-gurgaon',
  path: '/photo-booth-rental-gurgaon',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoBoothRentalNoidaRoute = PhotoBoothRentalNoidaRouteImport.update({
  id: '/photo-booth-rental-noida',
  path: '/photo-booth-rental-noida',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingPhotoBoothDelhiNcrRoute =
  WeddingPhotoBoothDelhiNcrRouteImport.update({
    id: '/wedding-photo-booth-delhi-ncr',
    path: '/wedding-photo-booth-delhi-ncr',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsBirthdaysRoute = EventsBirthdaysRouteImport.update({
  id: '/events/birthdays',
  path: '/events/birthdays',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCorporateRoute = EventsCorporateRouteImport.update({
  id: '/events/corporate',
  path: '/events/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsWeddingsRoute = EventsWeddingsRouteImport.update({
  id: '/events/weddings',
  path: '/events/weddings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/birthday-photo-booth-gurgaon': typeof BirthdayPhotoBoothGurgaonRoute
  '/contact': typeof ContactRoute
  '/corporate-photo-booth-noida': typeof CorporatePhotoBoothNoidaRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/our-work': typeof OurWorkRoute
  '/packages': typeof PackagesRoute
  '/photo-booth-rental-delhi': typeof PhotoBoothRentalDelhiRoute
  '/photo-booth-rental-delhi-ncr': typeof PhotoBoothRentalDelhiNcrRoute
  '/photo-booth-rental-greater-noida': typeof PhotoBoothRentalGreaterNoidaRoute
  '/photo-booth-rental-gurgaon': typeof PhotoBoothRentalGurgaonRoute
  '/photo-booth-rental-noida': typeof PhotoBoothRentalNoidaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/wedding-photo-booth-delhi-ncr': typeof WeddingPhotoBoothDelhiNcrRoute
  '/events/birthdays': typeof EventsBirthdaysRoute
  '/events/corporate': typeof EventsCorporateRoute
  '/events/weddings': typeof EventsWeddingsRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/birthday-photo-booth-gurgaon': typeof BirthdayPhotoBoothGurgaonRoute
  '/contact': typeof ContactRoute
  '/corporate-photo-booth-noida': typeof CorporatePhotoBoothNoidaRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/our-work': typeof OurWorkRoute
  '/packages': typeof PackagesRoute
  '/photo-booth-rental-delhi': typeof PhotoBoothRentalDelhiRoute
  '/photo-booth-rental-delhi-ncr': typeof PhotoBoothRentalDelhiNcrRoute
  '/photo-booth-rental-greater-noida': typeof PhotoBoothRentalGreaterNoidaRoute
  '/photo-booth-rental-gurgaon': typeof PhotoBoothRentalGurgaonRoute
  '/photo-booth-rental-noida': typeof PhotoBoothRentalNoidaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/wedding-photo-booth-delhi-ncr': typeof WeddingPhotoBoothDelhiNcrRoute
  '/events/birthdays': typeof EventsBirthdaysRoute
  '/events/corporate': typeof EventsCorporateRoute
  '/events/weddings': typeof EventsWeddingsRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/birthday-photo-booth-gurgaon': typeof BirthdayPhotoBoothGurgaonRoute
  '/contact': typeof ContactRoute
  '/corporate-photo-booth-noida': typeof CorporatePhotoBoothNoidaRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/our-work': typeof OurWorkRoute
  '/packages': typeof PackagesRoute
  '/photo-booth-rental-delhi': typeof PhotoBoothRentalDelhiRoute
  '/photo-booth-rental-delhi-ncr': typeof PhotoBoothRentalDelhiNcrRoute
  '/photo-booth-rental-greater-noida': typeof PhotoBoothRentalGreaterNoidaRoute
  '/photo-booth-rental-gurgaon': typeof PhotoBoothRentalGurgaonRoute
  '/photo-booth-rental-noida': typeof PhotoBoothRentalNoidaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/wedding-photo-booth-delhi-ncr': typeof WeddingPhotoBoothDelhiNcrRoute
  '/events/birthdays': typeof EventsBirthdaysRoute
  '/events/corporate': typeof EventsCorporateRoute
  '/events/weddings': typeof EventsWeddingsRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/birthday-photo-booth-gurgaon'
    | '/contact'
    | '/corporate-photo-booth-noida'
    | '/experiences'
    | '/faq'
    | '/our-work'
    | '/packages'
    | '/photo-booth-rental-delhi'
    | '/photo-booth-rental-delhi-ncr'
    | '/photo-booth-rental-greater-noida'
    | '/photo-booth-rental-gurgaon'
    | '/photo-booth-rental-noida'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/wedding-photo-booth-delhi-ncr'
    | '/events/birthdays'
    | '/events/corporate'
    | '/events/weddings'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/birthday-photo-booth-gurgaon'
    | '/contact'
    | '/corporate-photo-booth-noida'
    | '/experiences'
    | '/faq'
    | '/our-work'
    | '/packages'
    | '/photo-booth-rental-delhi'
    | '/photo-booth-rental-delhi-ncr'
    | '/photo-booth-rental-greater-noida'
    | '/photo-booth-rental-gurgaon'
    | '/photo-booth-rental-noida'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/wedding-photo-booth-delhi-ncr'
    | '/events/birthdays'
    | '/events/corporate'
    | '/events/weddings'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/birthday-photo-booth-gurgaon'
    | '/contact'
    | '/corporate-photo-booth-noida'
    | '/experiences'
    | '/faq'
    | '/our-work'
    | '/packages'
    | '/photo-booth-rental-delhi'
    | '/photo-booth-rental-delhi-ncr'
    | '/photo-booth-rental-greater-noida'
    | '/photo-booth-rental-gurgaon'
    | '/photo-booth-rental-noida'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/wedding-photo-booth-delhi-ncr'
    | '/events/birthdays'
    | '/events/corporate'
    | '/events/weddings'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BirthdayPhotoBoothGurgaonRoute: typeof BirthdayPhotoBoothGurgaonRoute
  ContactRoute: typeof ContactRoute
  CorporatePhotoBoothNoidaRoute: typeof CorporatePhotoBoothNoidaRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FaqRoute: typeof FaqRoute
  OurWorkRoute: typeof OurWorkRoute
  PackagesRoute: typeof PackagesRoute
  PhotoBoothRentalDelhiRoute: typeof PhotoBoothRentalDelhiRoute
  PhotoBoothRentalDelhiNcrRoute: typeof PhotoBoothRentalDelhiNcrRoute
  PhotoBoothRentalGreaterNoidaRoute: typeof PhotoBoothRentalGreaterNoidaRoute
  PhotoBoothRentalGurgaonRoute: typeof PhotoBoothRentalGurgaonRoute
  PhotoBoothRentalNoidaRoute: typeof PhotoBoothRentalNoidaRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  WeddingPhotoBoothDelhiNcrRoute: typeof WeddingPhotoBoothDelhiNcrRoute
  EventsBirthdaysRoute: typeof EventsBirthdaysRoute
  EventsCorporateRoute: typeof EventsCorporateRoute
  EventsWeddingsRoute: typeof EventsWeddingsRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthday-photo-booth-gurgaon': {
      id: '/birthday-photo-booth-gurgaon'
      path: '/birthday-photo-booth-gurgaon'
      fullPath: '/birthday-photo-booth-gurgaon'
      preLoaderRoute: typeof BirthdayPhotoBoothGurgaonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-photo-booth-noida': {
      id: '/corporate-photo-booth-noida'
      path: '/corporate-photo-booth-noida'
      fullPath: '/corporate-photo-booth-noida'
      preLoaderRoute: typeof CorporatePhotoBoothNoidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-booth-rental-delhi': {
      id: '/photo-booth-rental-delhi'
      path: '/photo-booth-rental-delhi'
      fullPath: '/photo-booth-rental-delhi'
      preLoaderRoute: typeof PhotoBoothRentalDelhiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-booth-rental-delhi-ncr': {
      id: '/photo-booth-rental-delhi-ncr'
      path: '/photo-booth-rental-delhi-ncr'
      fullPath: '/photo-booth-rental-delhi-ncr'
      preLoaderRoute: typeof PhotoBoothRentalDelhiNcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-booth-rental-greater-noida': {
      id: '/photo-booth-rental-greater-noida'
      path: '/photo-booth-rental-greater-noida'
      fullPath: '/photo-booth-rental-greater-noida'
      preLoaderRoute: typeof PhotoBoothRentalGreaterNoidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-booth-rental-gurgaon': {
      id: '/photo-booth-rental-gurgaon'
      path: '/photo-booth-rental-gurgaon'
      fullPath: '/photo-booth-rental-gurgaon'
      preLoaderRoute: typeof PhotoBoothRentalGurgaonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-booth-rental-noida': {
      id: '/photo-booth-rental-noida'
      path: '/photo-booth-rental-noida'
      fullPath: '/photo-booth-rental-noida'
      preLoaderRoute: typeof PhotoBoothRentalNoidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-photo-booth-delhi-ncr': {
      id: '/wedding-photo-booth-delhi-ncr'
      path: '/wedding-photo-booth-delhi-ncr'
      fullPath: '/wedding-photo-booth-delhi-ncr'
      preLoaderRoute: typeof WeddingPhotoBoothDelhiNcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/birthdays': {
      id: '/events/birthdays'
      path: '/events/birthdays'
      fullPath: '/events/birthdays'
      preLoaderRoute: typeof EventsBirthdaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/corporate': {
      id: '/events/corporate'
      path: '/events/corporate'
      fullPath: '/events/corporate'
      preLoaderRoute: typeof EventsCorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/weddings': {
      id: '/events/weddings'
      path: '/events/weddings'
      fullPath: '/events/weddings'
      preLoaderRoute: typeof EventsWeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BirthdayPhotoBoothGurgaonRoute: BirthdayPhotoBoothGurgaonRoute,
  ContactRoute: ContactRoute,
  CorporatePhotoBoothNoidaRoute: CorporatePhotoBoothNoidaRoute,
  ExperiencesRoute: ExperiencesRoute,
  FaqRoute: FaqRoute,
  OurWorkRoute: OurWorkRoute,
  PackagesRoute: PackagesRoute,
  PhotoBoothRentalDelhiRoute: PhotoBoothRentalDelhiRoute,
  PhotoBoothRentalDelhiNcrRoute: PhotoBoothRentalDelhiNcrRoute,
  PhotoBoothRentalGreaterNoidaRoute: PhotoBoothRentalGreaterNoidaRoute,
  PhotoBoothRentalGurgaonRoute: PhotoBoothRentalGurgaonRoute,
  PhotoBoothRentalNoidaRoute: PhotoBoothRentalNoidaRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  WeddingPhotoBoothDelhiNcrRoute: WeddingPhotoBoothDelhiNcrRoute,
  EventsBirthdaysRoute: EventsBirthdaysRoute,
  EventsCorporateRoute: EventsCorporateRoute,
  EventsWeddingsRoute: EventsWeddingsRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
